service: dnipro-slay-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    MONGODB_USER: ${env:MONGODB_USER}
    MONGODB_PASSWORD: ${env:MONGODB_PASSWORD}
    MONGODB_URL: ${env:MONGODB_URL}
    MONGODB_DB: ${env:MONGODB_DB}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    TOKEN: ${env:TOKEN}

package:
  patterns:
    - '!**'
    - dist/**
    - node_modules/**
    - package.json
    - package-lock.json

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi: '*'
  parse:
    handler: dist/handlers/parseHandler.parseHandler
    events:
      - schedule:
          rate: cron(0 0,6,12,18 * * ? *)
          enabled: true
